ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
-- CREACION DE USUARIO
DROP USER EJEMPLO CASCADE;

CREATE USER EJEMPLO IDENTIFIED BY "EJEMPLO"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- ROLES
GRANT "RESOURCE" TO "EJEMPLO" ;
GRANT "CONNECT" TO "EJEMPLO" ;

-- SYSTEM PRIVILEGES
GRANT DEBUG CONNECT SESSION TO "EJEMPLO" ;
GRANT DEBUG ANY PROCEDURE TO "EJEMPLO" ;
GRANT CREATE ROLE TO EJEMPLO ;
GRANT CREATE TRIGGER TO EJEMPLO ;
GRANT ALTER SESSION TO EJEMPLO ;
GRANT CREATE MATERIALIZED VIEW TO EJEMPLO ;
GRANT CREATE VIEW TO EJEMPLO ;
GRANT CREATE SESSION TO EJEMPLO ;
GRANT CREATE TABLE TO EJEMPLO ;
--GRANT CREATE ANY TABLE;
GRANT CREATE TYPE TO EJEMPLO ;
GRANT CREATE PUBLIC SYNONYM TO EJEMPLO ;
GRANT CREATE SYNONYM TO EJEMPLO ;
GRANT CREATE SEQUENCE TO EJEMPLO ;
GRANT CREATE DATABASE LINK TO EJEMPLO ;
GRANT UNLIMITED TABLESPACE TO EJEMPLO ;
GRANT CREATE PROCEDURE TO EJEMPLO ;