ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
-- CREACION DE USUARIO
DROP USER COLEGIO CASCADE;
CREATE USER COLEGIO IDENTIFIED BY "colegio";

-- ROLES
GRANT "RESOURCE" TO "COLEGIO" ;
GRANT "CONNECT" TO "COLEGIO" ;

-- SYSTEM PRIVILEGES
-- SYSTEM PRIVILEGES
GRANT DEBUG CONNECT SESSION TO "COLEGIO" ;
GRANT DEBUG ANY PROCEDURE TO "COLEGIO" ;
GRANT CREATE ROLE TO COLEGIO ;
GRANT CREATE TRIGGER TO COLEGIO ;
GRANT ALTER SESSION TO COLEGIO ;
GRANT CREATE MATERIALIZED VIEW TO COLEGIO ;
GRANT CREATE VIEW TO COLEGIO ;
GRANT CREATE SESSION TO COLEGIO ;
GRANT CREATE TABLE TO COLEGIO ;
--GRANT CREATE ANY TABLE;
GRANT CREATE TYPE TO COLEGIO ;
GRANT CREATE PUBLIC SYNONYM TO COLEGIO ;
GRANT CREATE SYNONYM TO COLEGIO ;
GRANT CREATE SEQUENCE TO COLEGIO ;
GRANT CREATE DATABASE LINK TO COLEGIO ;
GRANT UNLIMITED TABLESPACE TO COLEGIO ;
GRANT CREATE PROCEDURE TO COLEGIO ;