package clases;
// Generated 26 dic 2023 15:04:23 by Hibernate Tools 5.6.15.Final

import java.math.BigInteger;
import java.util.Date;

/**
 * Empleados generated by hbm2java
 */
@SuppressWarnings("serial")
public class Empleados implements java.io.Serializable {

	private BigInteger empNo;
	private Departamentos departamentos;
	private String apellido;
	private String oficio;
	private BigInteger dir;
	private Date fechaAlt;
	private Double salario;
	private Double comision;

	public Empleados() {
	}

	public Empleados(BigInteger empNo, Departamentos departamentos) {
		this.empNo = empNo;
		this.departamentos = departamentos;
	}

	public Empleados(BigInteger empNo, Departamentos departamentos, String apellido, String oficio, BigInteger dir,
			Date fechaAlt, Double salario, Double comision) {
		this.empNo = empNo;
		this.departamentos = departamentos;
		this.apellido = apellido;
		this.oficio = oficio;
		this.dir = dir;
		this.fechaAlt = fechaAlt;
		this.salario = salario;
		this.comision = comision;
	}

	public BigInteger getEmpNo() {
		return this.empNo;
	}

	public void setEmpNo(BigInteger empNo) {
		this.empNo = empNo;
	}

	public Departamentos getDepartamentos() {
		return this.departamentos;
	}

	public void setDepartamentos(Departamentos departamentos) {
		this.departamentos = departamentos;
	}

	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	public String getOficio() {
		return this.oficio;
	}

	public void setOficio(String oficio) {
		this.oficio = oficio;
	}

	public BigInteger getDir() {
		return this.dir;
	}

	public void setDir(BigInteger dir) {
		this.dir = dir;
	}

	public Date getFechaAlt() {
		return this.fechaAlt;
	}

	public void setFechaAlt(Date fechaAlt) {
		this.fechaAlt = fechaAlt;
	}

	public Double getSalario() {
		return this.salario;
	}

	public void setSalario(Double salario) {
		this.salario = salario;
	}

	public Double getComision() {
		return this.comision;
	}

	public void setComision(Double comision) {
		this.comision = comision;
	}

}
