ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
-- CREACION DE USUARIO
DROP USER PROYECTOS CASCADE;

CREATE USER PROYECTOS IDENTIFIED BY "proyectos"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- ROLES
GRANT "RESOURCE" TO "PROYECTOS" ;
GRANT "CONNECT" TO "PROYECTOS" ;

-- SYSTEM PRIVILEGES
GRANT DEBUG CONNECT SESSION TO "PROYECTOS" ;
GRANT DEBUG ANY PROCEDURE TO "PROYECTOS" ;
GRANT CREATE ROLE TO PROYECTOS ;
GRANT CREATE TRIGGER TO PROYECTOS ;
GRANT ALTER SESSION TO PROYECTOS ;
GRANT CREATE MATERIALIZED VIEW TO PROYECTOS ;
GRANT CREATE VIEW TO PROYECTOS ;
GRANT CREATE SESSION TO PROYECTOS ;
GRANT CREATE TABLE TO PROYECTOS ;
--GRANT CREATE ANY TABLE;
GRANT CREATE TYPE TO PROYECTOS ;
GRANT CREATE PUBLIC SYNONYM TO PROYECTOS ;
GRANT CREATE SYNONYM TO PROYECTOS ;
GRANT CREATE SEQUENCE TO PROYECTOS ;
GRANT CREATE DATABASE LINK TO PROYECTOS ;
GRANT UNLIMITED TABLESPACE TO PROYECTOS ;
GRANT CREATE PROCEDURE TO PROYECTOS ;