package clases;
// Generated 18 ene 2024 1:54:53 by Hibernate Tools 5.6.15.Final

import java.math.BigInteger;
import java.util.HashSet;
import java.util.Set;

/**
 * Clientes generated by hbm2java
 */
public class Clientes implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigInteger codcliente;
	private String nombre;
	private String poblacion;
	private String tlf;
	private Set<Compras> comprases = new HashSet<Compras>(0);
	private Set<Detcompras> detcomprases = new HashSet<Detcompras>(0);

	public Clientes() {
	}

	public Clientes(BigInteger codcliente) {
		this.codcliente = codcliente;
	}

	public Clientes(BigInteger codcliente, String nombre, String poblacion, String tlf, Set<Compras> comprases,
			Set<Detcompras> detcomprases) {
		this.codcliente = codcliente;
		this.nombre = nombre;
		this.poblacion = poblacion;
		this.tlf = tlf;
		this.comprases = comprases;
		this.detcomprases = detcomprases;
	}

	public BigInteger getCodcliente() {
		return this.codcliente;
	}

	public void setCodcliente(BigInteger codcliente) {
		this.codcliente = codcliente;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getPoblacion() {
		return this.poblacion;
	}

	public void setPoblacion(String poblacion) {
		this.poblacion = poblacion;
	}

	public String getTlf() {
		return this.tlf;
	}

	public void setTlf(String tlf) {
		this.tlf = tlf;
	}

	public Set<Compras> getComprases() {
		return this.comprases;
	}

	public void setComprases(Set<Compras> comprases) {
		this.comprases = comprases;
	}

	public Set<Detcompras> getDetcomprases() {
		return this.detcomprases;
	}

	public void setDetcomprases(Set<Detcompras> detcomprases) {
		this.detcomprases = detcomprases;
	}

}
