package clases;
// Generated 18 ene 2024 1:54:53 by Hibernate Tools 5.6.15.Final

import java.math.BigInteger;

/**
 * Detcompras generated by hbm2java
 */
public class Detcompras implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3638315960118790363L;
	private DetcomprasId id;
	private Compras compras;
	private Clientes clientes;
	private Productos productos;
	private BigInteger unidades;

	public Detcompras() {
	}

	public Detcompras(DetcomprasId id, Compras compras, Productos productos) {
		this.id = id;
		this.compras = compras;
		this.productos = productos;
	}

	public Detcompras(DetcomprasId id, Compras compras, Clientes clientes, Productos productos, BigInteger unidades) {
		this.id = id;
		this.compras = compras;
		this.clientes = clientes;
		this.productos = productos;
		this.unidades = unidades;
	}

	public DetcomprasId getId() {
		return this.id;
	}

	public void setId(DetcomprasId id) {
		this.id = id;
	}

	public Compras getCompras() {
		return this.compras;
	}

	public void setCompras(Compras compras) {
		this.compras = compras;
	}

	public Clientes getClientes() {
		return this.clientes;
	}

	public void setClientes(Clientes clientes) {
		this.clientes = clientes;
	}

	public Productos getProductos() {
		return this.productos;
	}

	public void setProductos(Productos productos) {
		this.productos = productos;
	}

	public BigInteger getUnidades() {
		return this.unidades;
	}

	public void setUnidades(BigInteger unidades) {
		this.unidades = unidades;
	}

}
