package clases;
// Generated 18 ene 2024 1:54:53 by Hibernate Tools 5.6.15.Final

import java.math.BigInteger;

/**
 * DetcomprasId generated by hbm2java
 */
public class DetcomprasId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8447698823606772659L;
	private BigInteger numcompra;
	private BigInteger codproducto;

	public DetcomprasId() {
	}

	public DetcomprasId(BigInteger numcompra, BigInteger codproducto) {
		this.numcompra = numcompra;
		this.codproducto = codproducto;
	}

	public BigInteger getNumcompra() {
		return this.numcompra;
	}

	public void setNumcompra(BigInteger numcompra) {
		this.numcompra = numcompra;
	}

	public BigInteger getCodproducto() {
		return this.codproducto;
	}

	public void setCodproducto(BigInteger codproducto) {
		this.codproducto = codproducto;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DetcomprasId))
			return false;
		DetcomprasId castOther = (DetcomprasId) other;

		return ((this.getNumcompra() == castOther.getNumcompra()) || (this.getNumcompra() != null
				&& castOther.getNumcompra() != null && this.getNumcompra().equals(castOther.getNumcompra())))
				&& ((this.getCodproducto() == castOther.getCodproducto())
						|| (this.getCodproducto() != null && castOther.getCodproducto() != null
								&& this.getCodproducto().equals(castOther.getCodproducto())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getNumcompra() == null ? 0 : this.getNumcompra().hashCode());
		result = 37 * result + (getCodproducto() == null ? 0 : this.getCodproducto().hashCode());
		return result;
	}

}
