package clases;
// Generated 18 ene 2024 1:54:53 by Hibernate Tools 5.6.15.Final

import java.math.BigInteger;
import java.util.HashSet;
import java.util.Set;

/**
 * Productos generated by hbm2java
 */
public class Productos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -53915207763740180L;
	private BigInteger codproducto;
	private String denominacion;
	private String tipo;
	private Double pvp;
	private BigInteger stock;
	private Set<Detcompras> detcomprases = new HashSet<Detcompras>(0);

	public Productos() {
	}

	public Productos(BigInteger codproducto) {
		this.codproducto = codproducto;
	}

	public Productos(BigInteger codproducto, String denominacion, String tipo, Double pvp, BigInteger stock,
			Set<Detcompras> detcomprases) {
		this.codproducto = codproducto;
		this.denominacion = denominacion;
		this.tipo = tipo;
		this.pvp = pvp;
		this.stock = stock;
		this.detcomprases = detcomprases;
	}

	public BigInteger getCodproducto() {
		return this.codproducto;
	}

	public void setCodproducto(BigInteger codproducto) {
		this.codproducto = codproducto;
	}

	public String getDenominacion() {
		return this.denominacion;
	}

	public void setDenominacion(String denominacion) {
		this.denominacion = denominacion;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public Double getPvp() {
		return this.pvp;
	}

	public void setPvp(Double pvp) {
		this.pvp = pvp;
	}

	public BigInteger getStock() {
		return this.stock;
	}

	public void setStock(BigInteger stock) {
		this.stock = stock;
	}

	public Set<Detcompras> getDetcomprases() {
		return this.detcomprases;
	}

	public void setDetcomprases(Set<Detcompras> detcomprases) {
		this.detcomprases = detcomprases;
	}

}
