package clases;
// Generated 1 ene 2024 11:36:06 by Hibernate Tools 6.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Alumnos generated by hbm2java
 */
@SuppressWarnings("serial")
public class Alumnos implements java.io.Serializable {

	private int numAlumno;
	private Cursos cursos;
	private String nombre;
	private String direccion;
	private String tlf;
	private Double notaMedia;
	private Set<Evaluaciones> evaluacioneses = new HashSet<>(0);

	public Alumnos() {
	}

	public Alumnos(int numAlumno, Cursos cursos, String nombre, String direccion, String tlf, Double notaMedia,
			Set<Evaluaciones> evaluacioneses) {
		this.numAlumno = numAlumno;
		this.cursos = cursos;
		this.nombre = nombre;
		this.direccion = direccion;
		this.tlf = tlf;
		this.notaMedia = notaMedia;
		this.evaluacioneses = evaluacioneses;
	}

	public int getNumAlumno() {
		return this.numAlumno;
	}

	public void setNumAlumno(int numAlumno) {
		this.numAlumno = numAlumno;
	}

	public Cursos getCursos() {
		return this.cursos;
	}

	public void setCursos(Cursos cursos) {
		this.cursos = cursos;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getTlf() {
		return this.tlf;
	}

	public void setTlf(String tlf) {
		this.tlf = tlf;
	}

	public Double getNotaMedia() {
		return this.notaMedia;
	}

	public void setNotaMedia(Double notaMedia) {
		this.notaMedia = notaMedia;
	}

	public Set<Evaluaciones> getEvaluacioneses() {
		return this.evaluacioneses;
	}

	public void setEvaluacioneses(Set<Evaluaciones> evaluacioneses) {
		this.evaluacioneses = evaluacioneses;
	}

}
