package clases;
// Generated 1 ene 2024 11:36:06 by Hibernate Tools 6.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Asignaturas generated by hbm2java
 */
@SuppressWarnings("serial")
public class Asignaturas implements java.io.Serializable {

	private int codAsig;
	private Departamentos departamentos;
	private Cursos cursos;
	private String nombre;
	private Set<?> evaluacioneses = new HashSet<Object>(0);

	public Asignaturas() {
	}

	public Asignaturas(int codAsig, Departamentos departamentos, Cursos cursos, String nombre, Set<?> evaluacioneses) {
		this.codAsig = codAsig;
		this.departamentos = departamentos;
		this.cursos = cursos;
		this.nombre = nombre;
		this.evaluacioneses = evaluacioneses;
	}

	public int getCodAsig() {
		return this.codAsig;
	}

	public void setCodAsig(int codAsig) {
		this.codAsig = codAsig;
	}

	public Departamentos getDepartamentos() {
		return this.departamentos;
	}

	public void setDepartamentos(Departamentos departamentos) {
		this.departamentos = departamentos;
	}

	public Cursos getCursos() {
		return this.cursos;
	}

	public void setCursos(Cursos cursos) {
		this.cursos = cursos;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set<?> getEvaluacioneses() {
		return this.evaluacioneses;
	}

	public void setEvaluacioneses(Set<?> evaluacioneses) {
		this.evaluacioneses = evaluacioneses;
	}

}
