package clases;
// Generated 1 ene 2024 11:36:06 by Hibernate Tools 6.3.1.Final

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.*;

/**
 * Centros generated by hbm2java
 */
@SuppressWarnings("serial")
public class Centros implements java.io.Serializable {
	@Id
	@Column(name = "COD-CENTRO")
	private int codCentro;
	private String nombre;
	private String localidad;
	private String tlf;
	private Integer numAlumnos;
	private Integer numCursos;
	private Integer presupuesto;
	private Set<?> cursoses = new HashSet<Object>(0);

	public Centros() {
	}

	public Centros(int codCentro, String nombre, String localidad, String tlf, Integer numAlumnos, Integer numCursos,
			Integer presupuesto, Set<?> cursoses) {
		this.codCentro = codCentro;
		this.nombre = nombre;
		this.localidad = localidad;
		this.tlf = tlf;
		this.numAlumnos = numAlumnos;
		this.numCursos = numCursos;
		this.presupuesto = presupuesto;
		this.cursoses = cursoses;
	}

	public int getCodCentro() {
		return this.codCentro;
	}

	public void setCodCentro(int codCentro) {
		this.codCentro = codCentro;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getLocalidad() {
		return this.localidad;
	}

	public void setLocalidad(String localidad) {
		this.localidad = localidad;
	}

	public String getTlf() {
		return this.tlf;
	}

	public void setTlf(String tlf) {
		this.tlf = tlf;
	}

	public Integer getNumAlumnos() {
		return this.numAlumnos;
	}

	public void setNumAlumnos(Integer numAlumnos) {
		this.numAlumnos = numAlumnos;
	}

	public Integer getNumCursos() {
		return this.numCursos;
	}

	public void setNumCursos(Integer numCursos) {
		this.numCursos = numCursos;
	}

	public Integer getPresupuesto() {
		return this.presupuesto;
	}

	public void setPresupuesto(Integer presupuesto) {
		this.presupuesto = presupuesto;
	}

	public Set<?> getCursoses() {
		return this.cursoses;
	}

	public void setCursoses(Set<?> cursoses) {
		this.cursoses = cursoses;
	}

}
