package clases;
// Generated 1 ene 2024 11:36:06 by Hibernate Tools 6.3.1.Final

/**
 * EvaluacionesId generated by hbm2java
 */
@SuppressWarnings("serial")
public class EvaluacionesId implements java.io.Serializable {

	private int codAsig;
	private int codEvaluacion;
	private int numAlumno;

	public EvaluacionesId() {
	}

	public EvaluacionesId(int codAsig, int codEvaluacion, int numAlumno) {
		this.codAsig = codAsig;
		this.codEvaluacion = codEvaluacion;
		this.numAlumno = numAlumno;
	}

	public int getCodAsig() {
		return this.codAsig;
	}

	public void setCodAsig(int codAsig) {
		this.codAsig = codAsig;
	}

	public int getCodEvaluacion() {
		return this.codEvaluacion;
	}

	public void setCodEvaluacion(int codEvaluacion) {
		this.codEvaluacion = codEvaluacion;
	}

	public int getNumAlumno() {
		return this.numAlumno;
	}

	public void setNumAlumno(int numAlumno) {
		this.numAlumno = numAlumno;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EvaluacionesId))
			return false;
		EvaluacionesId castOther = (EvaluacionesId) other;

		return (this.getCodAsig() == castOther.getCodAsig())
				&& (this.getCodEvaluacion() == castOther.getCodEvaluacion())
				&& (this.getNumAlumno() == castOther.getNumAlumno());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodAsig();
		result = 37 * result + this.getCodEvaluacion();
		result = 37 * result + this.getNumAlumno();
		return result;
	}

}
